-- =========================================================
-- CONVITE DIGITAL
-- Migration: 001_initial_schema.sql
-- =========================================================

-- =========================================================
-- 1. PROFILES
-- Complementa o usuário criado pelo Supabase Auth
-- =========================================================

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 2. EVENT TYPES
-- Exemplos: aniversário, casamento, chá de bebê...
-- =========================================================

create table public.event_types (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 3. THEMES
-- Tema visual independente do tipo de evento
-- =========================================================

create table public.themes (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  category text,
  thumbnail text,
  preview_image text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 4. INVITATIONS
-- Convites criados pelos usuários
-- =========================================================

create table public.invitations (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null
    references public.profiles(id)
    on delete cascade,

  event_type_id bigint
    references public.event_types(id)
    on delete set null,

  theme_id bigint
    references public.themes(id)
    on delete set null,

  slug text not null unique,

  title text,
  description text,
  story text,

  event_date date,
  event_time time,

  is_online boolean not null default false,
  online_platform text,
  online_url text,

  location text,
  address text,
  city text,
  state text,

  pix_key text,
  pix_name text,
  pix_qrcode text,

  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 5. INVITATION PHOTOS
-- Fotos utilizadas no convite
-- =========================================================

create table public.invitation_photos (
  id uuid primary key default gen_random_uuid(),

  invitation_id uuid not null
    references public.invitations(id)
    on delete cascade,

  url text not null,

  type text not null default 'gallery'
    check (
      type in (
        'cover',
        'story',
        'timeline',
        'gallery'
      )
    ),

  position integer not null default 0,

  caption text,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 6. TIMELINE
-- Linha do tempo / história do evento
-- =========================================================

create table public.timeline_items (
  id uuid primary key default gen_random_uuid(),

  invitation_id uuid not null
    references public.invitations(id)
    on delete cascade,

  title text not null,
  description text,

  date date,

  image_url text,

  position integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 7. GIFTS
-- Sugestões de presentes
-- =========================================================

create table public.gifts (
  id uuid primary key default gen_random_uuid(),

  invitation_id uuid not null
    references public.invitations(id)
    on delete cascade,

  name text not null,
  description text,

  value numeric(10,2),

  image text,

  position integer not null default 0,

  active boolean not null default true,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 8. INDEXES
-- Melhoram as consultas mais utilizadas
-- =========================================================

create index invitations_user_id_idx
  on public.invitations(user_id);

create index invitations_slug_idx
  on public.invitations(slug);

create index invitations_status_idx
  on public.invitations(status);

create index invitation_photos_invitation_id_idx
  on public.invitation_photos(invitation_id);

create index timeline_items_invitation_id_idx
  on public.timeline_items(invitation_id);

create index gifts_invitation_id_idx
  on public.gifts(invitation_id);


-- =========================================================
-- 9. UPDATED_AT
-- Atualiza automaticamente updated_at
-- =========================================================

create or replace function public.update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


create trigger profiles_updated_at
before update on public.profiles
for each row
execute function public.update_updated_at();


create trigger themes_updated_at
before update on public.themes
for each row
execute function public.update_updated_at();


create trigger invitations_updated_at
before update on public.invitations
for each row
execute function public.update_updated_at();


create trigger timeline_items_updated_at
before update on public.timeline_items
for each row
execute function public.update_updated_at();


-- =========================================================
-- 10. PROFILE AUTOMÁTICO
-- Cria um profile quando um usuário se cadastra
-- =========================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    name,
    email
  )
  values (
    new.id,
    new.raw_user_meta_data ->> 'name',
    new.email
  );

  return new;
end;
$$;


create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();


-- =========================================================
-- 11. ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.event_types enable row level security;
alter table public.themes enable row level security;
alter table public.invitations enable row level security;
alter table public.invitation_photos enable row level security;
alter table public.timeline_items enable row level security;
alter table public.gifts enable row level security;


-- =========================================================
-- 12. PROFILES POLICIES
-- =========================================================

create policy "Users can view own profile"
on public.profiles
for select
using (
  auth.uid() = id
);


create policy "Users can update own profile"
on public.profiles
for update
using (
  auth.uid() = id
);


-- =========================================================
-- 13. EVENT TYPES POLICIES
-- Tipos de evento são públicos para leitura
-- =========================================================

create policy "Anyone can view active event types"
on public.event_types
for select
using (
  active = true
);


-- =========================================================
-- 14. THEMES POLICIES
-- Temas são públicos para leitura
-- =========================================================

create policy "Anyone can view active themes"
on public.themes
for select
using (
  active = true
);


-- =========================================================
-- 15. INVITATIONS POLICIES
-- =========================================================

create policy "Users can view own invitations"
on public.invitations
for select
using (
  auth.uid() = user_id
  or (
    status = 'published'
  )
);


create policy "Users can create own invitations"
on public.invitations
for insert
with check (
  auth.uid() = user_id
);


create policy "Users can update own invitations"
on public.invitations
for update
using (
  auth.uid() = user_id
)
with check (
  auth.uid() = user_id
);


create policy "Users can delete own invitations"
on public.invitations
for delete
using (
  auth.uid() = user_id
);


-- =========================================================
-- 16. INVITATION PHOTOS POLICIES
-- =========================================================

create policy "Users can view invitation photos"
on public.invitation_photos
for select
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = invitation_photos.invitation_id
    and (
      invitations.user_id = auth.uid()
      or invitations.status = 'published'
    )
  )
);


create policy "Users can add invitation photos"
on public.invitation_photos
for insert
with check (
  exists (
    select 1
    from public.invitations
    where invitations.id = invitation_photos.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can update invitation photos"
on public.invitation_photos
for update
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = invitation_photos.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can delete invitation photos"
on public.invitation_photos
for delete
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = invitation_photos.invitation_id
    and invitations.user_id = auth.uid()
  )
);


-- =========================================================
-- 17. TIMELINE POLICIES
-- =========================================================

create policy "Users can view timeline"
on public.timeline_items
for select
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = timeline_items.invitation_id
    and (
      invitations.user_id = auth.uid()
      or invitations.status = 'published'
    )
  )
);


create policy "Users can create timeline items"
on public.timeline_items
for insert
with check (
  exists (
    select 1
    from public.invitations
    where invitations.id = timeline_items.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can update timeline items"
on public.timeline_items
for update
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = timeline_items.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can delete timeline items"
on public.timeline_items
for delete
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = timeline_items.invitation_id
    and invitations.user_id = auth.uid()
  )
);


-- =========================================================
-- 18. GIFTS POLICIES
-- =========================================================

create policy "Users can view gifts"
on public.gifts
for select
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = gifts.invitation_id
    and (
      invitations.user_id = auth.uid()
      or invitations.status = 'published'
    )
  )
);


create policy "Users can create gifts"
on public.gifts
for insert
with check (
  exists (
    select 1
    from public.invitations
    where invitations.id = gifts.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can update gifts"
on public.gifts
for update
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = gifts.invitation_id
    and invitations.user_id = auth.uid()
  )
);


create policy "Users can delete gifts"
on public.gifts
for delete
using (
  exists (
    select 1
    from public.invitations
    where invitations.id = gifts.invitation_id
    and invitations.user_id = auth.uid()
  )
);